### ISSUE TITLE
wiring diagram is hard to read in Github.

### ISSUE THREAD

**Issue by Techie09** [Natureshadow/floppi-music#2]
curious to see how the wiring works. The link in the Readme doesnt seem to work either.

**Comment by Natureshadow** [comment]
Use a text editor.

**Comment by mirabilos** [comment]
… or the raw link: https://raw.githubusercontent.com/Natureshadow/floppi-music/master/doc/wiring.md

But even then, Firefox® doesn’t manage to get line spacing right… use [a text editor[(https://www.mirbsd.org/jupp.htm) in xterm instead.

**Comment by mirabilos** [comment]
(although maybe the `.md` file extension is incorrect and should be `.txt` or something)
